<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title><?php echo $data['title'] ?></title>
    <LINK rel="stylesheet" type="text/css" title="Style" href="../css/style.css">
</head>
<body>

<div id="container">
    <form action="netpeak_3_side.php" method="post">
        <input type="text" disabled value="<?php echo $data['result'] ?>"/>
        <br/><br/>
        <input type="submit" value="back"/>
        <br/>
    </form>

    <a href="index.php">Back to the menu</a>
</div>

</body>
</html>