<div id="menu">
    <h1><?php echo $data['title']; ?></h1>

    <table class="menu-table">
        <tr class="menu-tr">
            <td class="menu-td-name">Task 1</td>
            <td class="menu-td-name2">
                <a href="index.php?route=three_side">The definition of a third side of a right triangle</a>
            </td>
        </tr>
        <tr class="menu-tr">
            <td class="menu-td-name">Task 2</td>
            <td class="menu-td-name2">
                <a href="index.php?route=area">Calculating the area of a triangle</a>
            </td>
        </tr>
    </table>
</div>
