<table>
    <caption class="name-table"><?php echo $data['title'] ?> (for example 3, 4)</caption>
    <tr>
        <td>
            <img src="../public/img/triangle.png" width="300" height="276" alt="triangle"/><br/><br/>
        </td>
    </tr>
    <tr>
        <td>
            <form action="index.php?route=three_side" method="post">
                <table>
                    <tr>
                        <td>
                            A <input type="number" class="form_action" min="0" name="a"
                                     value="<?php echo $data['post']['a'] ?>"/>
                            <br/><br/>
                            B <input type="number" class="form_action" min="0" name="b"
                                     value="<?php echo $data['post']['b'] ?>"/>
                            <br/><br/>
                            C <input type="number" class="form_action" min="0" name="c"
                                     value="<?php echo $data['post']['c'] ?>"/>
                        </td>
                    </tr>
                    <tr>
                        <td align="right">
                            <input type="submit" value="submit"/> <br/>
                        </td>
                    </tr>
                </table>
            </form>
        </td>
    </tr>
    <tr>
        <td>
            <a href="index.php">Back to the menu</a>
        </td>
    </tr>
</table>